# -*- coding: utf-8; mode: shell-script; -*-

debug "Loading zprofile ..."

## Host specific
if [ -e "$HOME/.zprofile.local" ]; then
    debug "$HOME/.zprofile.local"
    source $HOME/.zprofile.local
fi
