export LANG=en_US.UTF-8
export PATH=/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin
export EDITOR='emacsclient -t'

## rbenv
export PATH=$HOME/.rbenv/bin:$PATH
if type rbenv &>/dev/null; then
    eval "$(rbenv init -)"
fi

## go
if [ ! -d $HOME/.go ]; then
    mkdir $HOME/.go
fi
export GOPATH=$HOME/.go
export PATH=$HOME/.go/bin:$PATH

## Heroku
export PATH="/usr/local/heroku/bin:$PATH"

## server specific profile
if [ -e $HOME/.zprofile.local ]; then
    source $HOME/.zprofile.local
fi

## Vagrant
export VAGRANT_DEFAULT_PROVIDER=virtualbox

## user specific PATHs
export PATH=$HOME/local/bin:$HOME/bin:$PATH
