# -*- coding: utf-8; mode: shell-script; -*-

source $HOME/.zsh.d/functions

export LANG=en_US.UTF-8
debug "Loading zshenv ..."

if [ "$TERM" != "screen-256color" ]; then
    export TERM=xterm-256color
fi

## Suppress password dialogs
# default: SSH_ASKPASS=/usr/libexec/openssh/gnome-ssh-askpass
unset SSH_ASKPASS


## PATH
typeset -U path fpath manpath

typeset -aUT BASEPATH basepath
basepath=({/usr/local,/usr,}/bin(N-/) {/usr/local,/usr,}/sbin(N-/))
path=($basepath)

# anyenv
path=($HOME/.anyenv/bin(N-/) $path)
if installed anyenv; then
    eval "$(anyenv init -)"
fi

# fzf
path=($HOME/.fzf/bin(N-/) $path)
manpath=($HOME/.fzf/man(N-/) $manpath)

# go
export GOPATH=$HOME/.go
path=($GOPATH/bin(N-/) $path)


## Host specific
if exists $HOME/.zshenv.local; then
    debug "$HOME/.zshenv.local"
    source $HOME/.zshenv.local
fi

## Disable loading rc files in /etc
# /etc/zprofile will reset PATH variable by path_helper
setopt no_global_rcs
