# -*- coding: utf-8; mode: shell-script; -*-

# Disable loading rc files in /etc
# /etc/zprofile will reset PATH variable by path_helper
setopt no_global_rcs

export LANG=en_US.UTF-8
if [ "$TERM" != "screen-256color" ]; then
    export TERM=xterm-256color
fi

export BASEPATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin
export PATH=$BASEPATH

export EDITOR='emacsclient -t'

## Suppress password dialogs
# default: SSH_ASKPASS=/usr/libexec/openssh/gnome-ssh-askpass
unset SSH_ASKPASS

## anyenv
export PATH=$HOME/.anyenv/bin:$PATH

## fzf
export PATH=$HOME/.fzf/bin:$PATH
export MANPATH=$HOME/.fzf/man:$MANPATH

## go
export GOPATH=$HOME/.go
export PATH=$HOME/.go/bin:$PATH

## server specific env
if [ -e $HOME/.zshenv.local ]; then
    source $HOME/.zshenv.local
fi
