# -*- coding: utf-8; mode: shell-script; -*-

function _load_configurations() {
    local rc
    for rc in $HOME/.zsh.d/*.zsh; do
        source $rc
    done

    ## server specific
    if [ -e $HOME/.zshrc.local ]; then
        source $HOME/.zshrc.local
    fi
}

_load_configurations

if [ "$TERM" != "screen-256color" ]; then
    zsh -c "$TMUX_NEW_COMMAND"
fi
