# -*- coding: utf-8; mode: shell-script; -*-

debug "Loading zshrc ..."

function _load_configurations() {
    local rc
    for rc in $HOME/.zsh.d/*.zsh; do
        debug "$rc"
        source $rc
    done

    ## server specific
    if [ -e "$HOME/.zshrc.local" ]; then
        debug "$HOME/.zshrc.local"
        source $HOME/.zshrc.local
    fi
}

_load_configurations

if [ "$TERM" != "screen-256color" ]; then
    debug "Starting tmux new session ..."
    zsh -c $TMUX_NEW_COMMAND
fi

debug "Done."
