# -*- coding: utf-8; mode: shell-script; -*-

debug "Loading zshrc ..."

function _load_configurations() {
    local config
    for config in $HOME/.zsh.d/*.zsh; do
        debug "$config"
        source $config
    done
}

_load_configurations

## Host specific
if [ -e "$HOME/.zshrc.local" ]; then
    debug "$HOME/.zshrc.local"
    source $HOME/.zshrc.local
fi

debug "Done."


## Start tmux session
if [ -z "$TMUX" ]; then
    debug "Starting tmux new session ..."
    bash -c $TMUX_NEW_COMMAND
fi
