# -*- coding: utf-8; mode: shell-script; -*-

debug "Loading zprofile ..."

export EDITOR=e
export LESS='-giMR'

HISTFILE=$HOME/.zhistory
HISTSIZE=10000
SAVEHIST=10000

## Host specific
if [[ -e $HOME/.config/zsh/zprofile.local ]]; then
    debug "$HOME/.config/zsh/zprofile.local"
    source $HOME/.config/zsh/zprofile.local
fi
