# -*- coding: utf-8; mode: shell-script; -*-

source $HOME/.config/zsh/functions

export LANG=en_US.UTF-8
debug "Loading zshenv ..."

if [ "$TERM" != "screen-256color" ]; then
    export TERM=xterm-256color
fi

## Suppress password dialogs
# default: SSH_ASKPASS=/usr/libexec/openssh/gnome-ssh-askpass
unset SSH_ASKPASS


## PATH
typeset -U path fpath manpath

typeset -aUT BASEPATH basepath
basepath=({/usr/local,/usr,}/bin(N-/) {/usr/local,/usr,}/sbin(N-/))
path=($basepath)

# go
export GOPATH=$HOME/.local/lib/go
path=($GOPATH/bin(N-/) $path)

# anyenv
export ANYENV_ROOT="$(ghq root)/github.com/riywo/anyenv"
if [[ -e $ANYENV_ROOT/bin/anyenv ]]; then
    eval "$($ANYENV_ROOT/bin/anyenv init -)"
fi

# fzf
path=($HOME/.fzf/bin(N-/) $path)
manpath=($HOME/.fzf/man(N-/) $manpath)

path=($HOME/.local/bin(N-/) $path)

## Host specific
if [[ -e $HOME/.config/zsh/zshenv.local ]]; then
    debug "$HOME/.config/zsh/zshenv.local"
    source $HOME/.config/zsh/zshenv.local
fi

## Disable loading rc files in /etc
# /etc/zprofile will reset PATH variable by path_helper
setopt NO_GLOBAL_RCS
