# -*- mode: shell-script; -*-

export LANG="en_US.UTF-8"
export DOTFILES_DEBUG=${DOTFILES_DEBUG:-0}


debug() {
    if [[ $DOTFILES_DEBUG -ne 0 ]]; then
        echo "$(date +'%b %d %T') debug: $@" >&2
    fi
}

source-if-exists() {
    local source_file_path=$1
    if [[ -e $source_file_path ]]; then
        debug "$source_file_path"
        source "$source_file_path"
    fi
}


debug "Loading zshenv ..."


# similar to XDG Base Directory Specification
export CONFIG_HOME="$HOME/.config"
export CACHE_HOME="$HOME/.cache"
export BIN_HOME="$HOME/.local/bin"
export LIB_HOME="$HOME/.local/lib"
export DATA_HOME="$HOME/.local/share"
export SRC_HOME="$HOME/.local/src"

export GOPATH="$LIB_HOME/go"
export ANYENV_ROOT="$SRC_HOME/github.com/riywo/anyenv"
export TMUX_PLUGIN_MANAGER_PATH="$DATA_HOME/tmux/plugins"

source-if-exists "$CONFIG_HOME/zsh/zshenv.local"
