# -*- mode: shell-script; -*-

debug "Loading zshrc ..."


load_files() {
    local dist=$(uname -s | tr '[:upper:]' '[:lower:]')
    local config

    for config in $1/[0-9][0-9]*.zsh(N); do
        source_if_exists "$config"
    done

    for config in $1/$dist-*.zsh(N); do
        source_if_exists "$config"
    done
}

load_files "$CONFIG_HOME/zsh"


source_if_exists "$CONFIG_HOME/zsh/zshrc.local"
debug "Done."
