# -*- coding: utf-8; mode: shell-script; -*-

debug "Loading zshrc ..."

_load_configurations() {
    local config
    for config in $HOME/.config/zsh/*.zsh; do
        debug "$config"
        source $config
    done
}

_load_configurations

## Host specific
if [[ -e $HOME/.config/zsh/zshrc.local ]]; then
    debug "$HOME/.config/zsh/zshrc.local"
    source $HOME/.config/zsh/zshrc.local
fi

debug "Done."
