# -*- mode: shell-script; -*-

export LANG="en_US.UTF-8"
export DOTFILES_DEBUG=${DOTFILES_DEBUG:-0}


debug() {
    if [[ $DOTFILES_DEBUG -ne 0 ]]; then
        echo "$(date +'%b %d %T') debug: $@" >&2
    fi
}

source-if-exists() {
    local source_file_path=$1
    if [[ -e $source_file_path ]]; then
        debug "$source_file_path"
        source "$source_file_path"
    fi
}


debug "Loading zshenv ..."

source-if-exists "$HOME/.config/zsh/zshenv.local"
