# -*- mode: shell-script; -*-

debug "Loading zshrc ..."


load-files() {
    local config

    for config in $1/[0-9][0-9]*.zsh(N); do
        source-if-exists "$config"
    done

    local dist=$(uname -s | tr '[:upper:]' '[:lower:]')
    for config in $1/$dist-*.zsh(N); do
        source-if-exists "$config"
    done
}

load-files "$HOME/.config/zsh"


source-if-exists "$HOME/.config/zsh/zshrc.local"
debug "Done."
