unsetopt promptcr
setopt prompt_subst

setopt append_history auto_list auto_menu auto_param_keys auto_param_slash auto_resume no_beep brace_ccl correct equals extended_glob no_flow_control hist_ignore_dups hist_ignore_space hist_verify no_hup ignore_eof interactive_comments list_types long_list_jobs magic_equal_subst mark_dirs multios numeric_glob_sort print_eightbit print_exit_value pushd_ignore_dups short_loops share_history hist_no_store pushd_silent

setopt transient_rprompt
