#!/bin/bash

function check_packages_installed() {
    local packages="curl git go"
    local require_packages

    local pkg
    for pkg in $packages; do
        if ! type "$pkg" &>/dev/null; then
            require_packages="$require_packages $pkg"
        fi
    done

    if [ -n "$require_packages" ]; then
        echo "!!! You need to install packages:$require_packages"
        exit 1
    fi
}

function not_exists() {
    echo "### Check exists: $1"
    test ! -e "$1"
}

function not_installed() {
    echo "### Check installed: $1"
    ! type "$1" &>/dev/null
}

function install_configurations() {
    # dotfiles repository
    local dotfiles_path="$HOME"/.ghq/github.com/speg03/dotfiles
    if not_exists "$dotfiles_path"; then
        echo "# Downloading dotfiles ..."
        git clone https://github.com/speg03/dotfiles "$dotfiles_path"
    fi
    echo

    local sources_path="$dotfiles_path"/sources
    cd "$sources_path" || exit 1
    local sources
    sources=$(ls)

    # symlinks
    local src
    for src in $sources; do
        if not_exists "$HOME"/."$src"; then
            echo "# Creating links to $src ..."
            ln -s "$sources_path"/"$src" "$HOME"/."$src"
        fi
    done
    echo

    # git completion
    if not_exists "$HOME"/.zsh.d/completion/_git; then
        echo "# Downloading completions for git ..."
        curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.zsh -o "$HOME"/.zsh.d/completion/_git
        curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash -o "$HOME"/.zsh.d/completion/git-completion.bash
    fi
    echo

    # docker completion
    if not_exists "$HOME"/.zsh.d/completion/_docker; then
        echo "# Downloading completions for docker ..."
        curl https://raw.githubusercontent.com/docker/docker/master/contrib/completion/zsh/_docker -o "$HOME"/.zsh.d/completion/_docker
    fi
    echo

    # git config
    if not_exists "$HOME"/.gitconfig.local; then
        echo "# Creating git configuration for local ..."
        git config -f "$HOME"/.gitconfig.local user.name 'Takahiro Yano'
        git config -f "$HOME"/.gitconfig.local user.email 'speg03@gmail.com'
    fi
    echo

    # netrc template
    if not_exists "$HOME"/.netrc; then
        echo "# Creating netrc template ..."
        {
            echo "#machine github.com"
            echo "#  login speg03"
            echo "#  password ACCESS_TOKEN"
        } >"$HOME"/.netrc
        chmod 0600 "$HOME"/.netrc
    fi
    echo
}

function install_tools() {
    # anyenv
    if not_exists "$HOME"/.anyenv; then
        echo "# Installing anyenv ..."
        git clone https://github.com/riywo/anyenv "$HOME"/.anyenv
        mkdir -p "$HOME"/.anyenv/plugins
        git clone https://github.com/znz/anyenv-update \
            "$HOME"/.anyenv/plugins/anyenv-update
    fi
    echo

    # load anyenv
    if not_installed pyenv; then
        echo "# Loading anyenv ..."
        export PATH="$HOME"/.anyenv/bin:"$PATH"
        eval "$(anyenv init -)"

        # pyenv
        echo "# Installing pyenv ..."
        anyenv install pyenv
        git clone https://github.com/yyuu/pyenv-virtualenv.git \
            "$HOME"/.anyenv/envs/pyenv/plugins/pyenv-virtualenv
    fi
    echo

    # fzf
    if not_exists "$HOME"/.fzf; then
        echo "# Installing fzf ..."
        git clone https://github.com/junegunn/fzf "$HOME"/.fzf
        "$HOME"/.fzf/install --bin
    fi
    echo

    # tpm
    if not_exists "$HOME"/.tmux/plugins/tpm; then
        echo "# Installing tpm ..."
        git clone https://github.com/tmux-plugins/tpm "$HOME"/.tmux/plugins/tpm
        "$HOME"/.tmux/plugins/tpm/bin/install_plugins
    fi
    echo

    # Go packages
    export GOPATH="$HOME"/.go
    export PATH="$HOME"/.go/bin:"$PATH"
    if not_installed ghq; then
        echo "# Installing ghq ..."
        go get github.com/motemen/ghq
    fi
}


function main() {
    check_packages_installed

    install_configurations
    install_tools
}

main
