#!/bin/bash
#
# Install my custom dotfiles


function msg() {
    echo "$@" >&2
}

function not_exists() {
    test ! -e "$1"
}

function not_installed() {
    ! type "$1" &>/dev/null
}

function check_packages_installed() {
    local packages="curl git go"
    local require_packages

    local pkg
    for pkg in $packages; do
        if not_installed "$pkg"; then
            require_packages="$require_packages $pkg"
        fi
    done

    if [ -n "$require_packages" ]; then
        msg "!!! You need to install packages:$require_packages"
        exit 1
    fi
}

function install_configurations() {
    # dotfiles repository
    local dotfiles_path="$HOME"/.ghq/github.com/speg03/dotfiles
    if not_exists "$dotfiles_path"; then
        msg "# Downloading dotfiles ..."
        git clone https://github.com/speg03/dotfiles "$dotfiles_path"
    fi

    # symlinks for bin
    mkdir -p "$HOME"/.local/bin
    if not_exists "$HOME"/.local/bin/mem-cpu-load; then
        msg "# Creating links to mem-cpu-load ..."
        ln -s "$dotfiles_path"/bin/mem-cpu-load "$HOME"/.local/bin/
    fi

    # symlinks for sources
    local source
    local source_path
    for source_path in $dotfiles_path/sources/*; do
        source=$(basename "$source_path")
        if not_exists "$HOME"/."$source"; then
            msg "# Creating links to $source ..."
            ln -s "$source_path" "$HOME"/."$source"
        fi
    done

    # git completion
    if not_exists "$HOME"/.zsh.d/completion/_git; then
        msg "# Downloading completions for git ..."
        curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.zsh -o "$HOME"/.zsh.d/completion/_git
        curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash -o "$HOME"/.zsh.d/completion/git-completion.bash
    fi

    # docker completion
    if not_exists "$HOME"/.zsh.d/completion/_docker; then
        msg "# Downloading completions for docker ..."
        curl https://raw.githubusercontent.com/docker/docker/master/contrib/completion/zsh/_docker -o "$HOME"/.zsh.d/completion/_docker
    fi

    # git config
    if not_exists "$HOME"/.gitconfig.local; then
        msg "# Creating git configuration for local ..."
        git config -f "$HOME"/.gitconfig.local user.name 'Takahiro Yano'
        git config -f "$HOME"/.gitconfig.local user.email 'speg03@gmail.com'
    fi

    # netrc template
    if not_exists "$HOME"/.netrc; then
        msg "# Creating netrc template ..."
        {
            echo "#machine github.com"
            echo "#  login speg03"
            echo "#  password ACCESS_TOKEN"
        } >"$HOME"/.netrc
        chmod 0600 "$HOME"/.netrc
    fi
}

function install_tools() {
    # anyenv
    if not_exists "$HOME"/.anyenv; then
        msg "# Installing anyenv ..."
        git clone https://github.com/riywo/anyenv "$HOME"/.anyenv
        mkdir -p "$HOME"/.anyenv/plugins
        git clone https://github.com/znz/anyenv-update \
            "$HOME"/.anyenv/plugins/anyenv-update
    fi

    # load anyenv
    if not_installed pyenv; then
        msg "# Loading anyenv ..."
        export PATH="$HOME"/.anyenv/bin:"$PATH"
        eval "$(anyenv init -)"

        # pyenv
        msg "# Installing pyenv ..."
        anyenv install pyenv
        git clone https://github.com/yyuu/pyenv-virtualenv.git \
            "$HOME"/.anyenv/envs/pyenv/plugins/pyenv-virtualenv
    fi

    # fzf
    if not_exists "$HOME"/.fzf; then
        msg "# Installing fzf ..."
        git clone https://github.com/junegunn/fzf "$HOME"/.fzf
        "$HOME"/.fzf/install --bin
    fi

    # tpm
    if not_exists "$HOME"/.tmux/plugins/tpm; then
        msg "# Installing tpm ..."
        git clone https://github.com/tmux-plugins/tpm "$HOME"/.tmux/plugins/tpm
        "$HOME"/.tmux/plugins/tpm/bin/install_plugins
    fi

    # Go packages
    export GOPATH="$HOME"/.go
    export PATH="$GOPATH"/bin:"$PATH"
    if not_installed ghq; then
        msg "# Installing ghq ..."
        go get github.com/motemen/ghq
    fi
}


function main() {
    check_packages_installed

    install_configurations
    install_tools
}

main
